## Análisi de Componentes Principales - Paso a Paso...
* Estandarizar los datos (para cada una de las m observaciones).
* Obtener los valores y vectores propios a partir de la matriz de covarianza o de correlaciones o incluso la técnica de singular vector descomposition.
* Ordenar los valore propios en orden descendiente y quedarnos con los p que se corresponden a los p mayores y así disminuir en número de variables del dataset: (p < m).
* Construir la matriz de proyeción W a partir de los p vectores propios.
* Transformar el datast oroginal X a través de W para así obtener datos en el subespacio dimencional de dimensión p, que será Y.

In [1]:
import pandas as pd
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

In [2]:
df = pd.read_csv("../../datasets/iris/iris.csv")
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values

In [4]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [5]:
tls.set_credentials_file(username = 'JorgeAlbertoGomezGomez', api_key = 'cwcOhrD6jCZAfCgJAYei')

In [6]:
traces = []
legend = {0: True, 1: True, 2: True, 3: True}

colors = {'setosa': 'rgb(255, 127, 20)',
         'versicolor': 'rgb(31, 220,120)',
         'virginica': 'rgb(44, 50, 180)'}

for col in range(4): 
    for key in colors:
        traces.append(Histogram(x = X[y == key, col], opacity = 0.7, 
                                xaxis = "x%s" %(col+1), marker = Marker(color = colors[key]),
                               name = key, showlegend = legend[col]))
    legend = {0:False, 1:False, 2:False, 3:False}
        
data = Data(traces)
layout = Layout(barmode = "overlay", 
                xaxis = XAxis(domain = [0,0.25], title = "Long. Sépalos (cm)"),
                xaxis2 = XAxis(domain = [0.3, 0.5], title = "Anch. Sépalos (cm)"),
                xaxis3 = XAxis(domain = [0.55, 0.75], title = "Long. Pétalos (cm)"),
                xaxis4 = XAxis(domain = [0.8,1.0], title = "Anch. Pétalos (cm)"),
                yaxis = YAxis(title = "Número de ejemplares"),
                title = "Distribución de los rasgos de las diferentes flores Iris")

fig = Figure(data = data, layout = layout)
py.iplot(fig)

c:\users\jorge\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_deprecations.py:426: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.


c:\users\jorge\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


c:\users\jorge\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_deprecations.py:531: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.lay

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
x_std = StandardScaler().fit_transform(X)
traces = []
legend = {0: True, 1: True, 2: True, 3: True}

colors = {'setosa': 'rgb(255, 127, 20)',
         'versicolor': 'rgb(31, 220,120)',
         'virginica': 'rgb(44, 50, 180)'}

for col in range(4): 
    for key in colors:
        traces.append(Histogram(x = x_std[y == key, col], opacity = 0.7, 
                                xaxis = "x%s" %(col+1), marker = Marker(color = colors[key]),
                               name = key, showlegend = legend[col]))
    legend = {0:False, 1:False, 2:False, 3:False}
        
data = Data(traces)
layout = Layout(barmode = "overlay", 
                xaxis = XAxis(domain = [0,0.25], title = "Long. Sépalos (cm)"),
                xaxis2 = XAxis(domain = [0.3, 0.5], title = "Anch. Sépalos (cm)"),
                xaxis3 = XAxis(domain = [0.55, 0.75], title = "Long. Pétalos (cm)"),
                xaxis4 = XAxis(domain = [0.8,1.0], title = "Anch. Pétalos (cm)"),
                yaxis = YAxis(title = "Número de ejemplares"),
                title = "Distribución de los rasgos de las diferentes flores Iris")

fig = Figure(data = data, layout = layout)
py.iplot(fig)

c:\users\jorge\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_deprecations.py:426: DeprecationWarning:

plotly.graph_objs.Marker is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Marker
  - plotly.graph_objs.histogram.selected.Marker
  - etc.


c:\users\jorge\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_deprecations.py:39: DeprecationWarning:

plotly.graph_objs.Data is deprecated.
Please replace it with a list or tuple of instances of the following types
  - plotly.graph_objs.Scatter
  - plotly.graph_objs.Bar
  - plotly.graph_objs.Area
  - plotly.graph_objs.Histogram
  - etc.


c:\users\jorge\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_deprecations.py:531: DeprecationWarning:

plotly.graph_objs.XAxis is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.XAxis
  - plotly.graph_objs.lay

# 1--------------------------------------------------------------------------------------------------------------
## Primera forma...
### 1 - Calculamos la descomposición de valores y vectores propios...

In [9]:
from IPython.display import display, Math, Latex

In [11]:
display(Math(r'\sigma_{jk} = \frac{1}{n - 1}\sum_{i = 1}^m (x_{ij} - \overline{x_j})(x_{ik} - \overline{x_k})'))

<IPython.core.display.Math object>

In [15]:
display(Math(r'\Sigma = \frac{1}{n - 1}((X - \overline{x})^T(X - \overline{x}))'))

<IPython.core.display.Math object>

In [16]:
display(Math(r'\overline{x} = \sum_{i = 1}^n x_i\in \mathbb R^m'))

<IPython.core.display.Math object>

In [17]:
import numpy as np

In [19]:
mean_vect = np.mean(x_std, axis = 0)
mean_vect

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [22]:
cov_matrix = (x_std - mean_vect).T.dot((x_std - mean_vect)) / (x_std.shape[0] - 1)
print("La matriz de covarianzas es \n%s" %cov_matrix)

La matriz de covarianzas es 
[[ 1.00671141 -0.11835884  0.87760447  0.82343066]
 [-0.11835884  1.00671141 -0.43131554 -0.36858315]
 [ 0.87760447 -0.43131554  1.00671141  0.96932762]
 [ 0.82343066 -0.36858315  0.96932762  1.00671141]]


In [23]:
np.cov(x_std.T)

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [24]:
eig_vals, eig_vectors = np.linalg.eig(cov_matrix)
print("Valores propios \n%s" %eig_vals)
print("Vectores propios \n%s" %eig_vectors)

Valores propios 
[2.93808505 0.9201649  0.14774182 0.02085386]
Vectores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


## Segunda Forma...
### 2 - Usando la matriz de Correlaciones...

In [25]:
corr_matrix = np.corrcoef(x_std.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [26]:
eig_vals_corr, eig_vectors_corr = np.linalg.eig(corr_matrix)
print("Valores propios \n%s" %eig_vals_corr)
print("Vectores propios \n%s" %eig_vectors_corr)

Valores propios 
[2.91849782 0.91403047 0.14675688 0.02071484]
Vectores propios 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [27]:
corr_matrix = np.corrcoef(X.T)
corr_matrix

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

## Tercera Forma...
### 3 - Singular Value Descomposition...

In [33]:
u, s, v = np.linalg.svd(x_std.T)
u

array([[-0.52106591, -0.37741762,  0.71956635,  0.26128628],
       [ 0.26934744, -0.92329566, -0.24438178, -0.12350962],
       [-0.5804131 , -0.02449161, -0.14212637, -0.80144925],
       [-0.56485654, -0.06694199, -0.63427274,  0.52359713]])

In [34]:
s

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [35]:
v

array([[ 1.08239531e-01,  9.94577561e-02,  1.12996303e-01, ...,
        -7.27030413e-02, -6.56112167e-02, -4.59137323e-02],
       [-4.09957970e-02,  5.75731483e-02,  2.92000319e-02, ...,
        -2.29793601e-02, -8.63643414e-02,  2.07800179e-03],
       [ 2.72186462e-02,  5.00034005e-02, -9.42089147e-03, ...,
        -3.84023516e-02, -1.98939364e-01, -1.12588405e-01],
       ...,
       [ 5.43380310e-02,  5.12936114e-03,  2.75184277e-02, ...,
         9.89532683e-01, -1.41206665e-02, -8.30595907e-04],
       [ 1.96438400e-03,  8.48544595e-02,  1.78604309e-01, ...,
        -1.25488246e-02,  9.52049996e-01, -2.19201906e-02],
       [ 2.46978090e-03,  5.83496936e-03,  1.49419118e-01, ...,
        -7.17729676e-04, -2.32048811e-02,  9.77300244e-01]])

# 2---------------------------------------------------------------------------------------------------------------
## Las componentes principales...

In [37]:
for ev in eig_vectors:
    print("La longitud del VP es: %s" %np.linalg.norm(ev))

La longitud del VP es: 0.9999999999999996
La longitud del VP es: 1.0000000000000002
La longitud del VP es: 1.0
La longitud del VP es: 0.9999999999999999


In [38]:
eigen_pairs = [(np.abs(eig_vals[i]), eig_vectors[:, i]) for i in range(len(eig_vals))]
eigen_pairs

[(2.938085050199993,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624872,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.14774182104494815,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.020853862176462592,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

### Ordenamos los vectores propios con valor propio de mayor a menor...

In [39]:
eigen_pairs.sort()
eigen_pairs.reverse()
eigen_pairs

[(2.938085050199993,
  array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])),
 (0.9201649041624872,
  array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])),
 (0.14774182104494815,
  array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])),
 (0.020853862176462592,
  array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]

In [40]:
print("Valores propios en orden descendiente:")
for ep in eigen_pairs:
    print(ep[0])

Valores propios en orden descendiente:
2.938085050199993
0.9201649041624872
0.14774182104494815
0.020853862176462592


In [41]:
total_sum = sum(eig_vals)
var_exp = [(i / total_sum) * 100 for i in sorted(eig_vals, reverse = True)]
cum_var_exp = np.cumsum(var_exp)

In [44]:
plot1 = Bar(x = ["CP %s" %i for i in range(1, 5)], y = var_exp, showlegend = False)
plot2 = Scatter(x = ["CP %s" %i for i in range(1, 5)], y = cum_var_exp, showlegend = True, name = "% de Varianza Explicada Acumulada")
data = Data([plot1, plot2])
layout = Layout(xaxis = XAxis(title = "Componentes Principales"), 
                yaxis = YAxis(title = "Porcentaje de varianza explicada"), 
                title = "Porcentaje de variabilidad explicada por cada componente principal")
fig = Figure(data = data, layout = layout)
py.iplot(fig)