# El método de k-means... 

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30, 3)
data

array([[0.41093358, 0.02488696, 0.02075255],
       [0.20032427, 0.26166865, 0.54130208],
       [0.62112598, 0.41089016, 0.1514737 ],
       [0.00482513, 0.47999396, 0.15961533],
       [0.12967658, 0.75552616, 0.07704467],
       [0.36562272, 0.52887091, 0.67357322],
       [0.27156994, 0.33119332, 0.08127979],
       [0.09910809, 0.06089496, 0.16518851],
       [0.25042725, 0.60140723, 0.84288547],
       [0.08972911, 0.9218175 , 0.36742448],
       [0.5225139 , 0.26175075, 0.63264868],
       [0.04631962, 0.09404978, 0.55849105],
       [0.81823755, 0.9305788 , 0.44956426],
       [0.37601835, 0.42337929, 0.58574747],
       [0.10881594, 0.34818649, 0.86751607],
       [0.78166224, 0.56136118, 0.5796316 ],
       [0.73393786, 0.5363969 , 0.44795522],
       [0.4176695 , 0.05839549, 0.85221652],
       [0.27531479, 0.11940562, 0.23374618],
       [0.42183192, 0.71654383, 0.94621383],
       [0.88328394, 0.17269992, 0.72471392],
       [0.65070899, 0.52537713, 0.03983436],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.00482513, 0.47999396, 0.15961533],
       [0.36562272, 0.52887091, 0.67357322]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 0, 1, 1]),
 array([0.6255632 , 0.34090509, 0.59311827, 0.        , 0.31356625,
        0.        , 0.31532662, 0.42960948, 0.21725136, 0.49558185,
        0.31247855, 0.55160474, 0.64529794, 0.13765869, 0.36906695,
        0.42774938, 0.43199094, 0.5059342 , 0.45681942, 0.33572831,
        0.63043341, 0.65846266, 0.78869023, 0.69969524, 0.31829861,
        0.34877508, 0.4528768 , 0.31317096, 0.45465333, 0.31059838]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[0.25606035, 0.39260354, 0.20442111],
        [0.4822919 , 0.42849764, 0.62514351]]), 0.3800528887332933)

In [8]:
kmeans(data, 2)

(array([[0.73616273, 0.56986848, 0.35439482],
        [0.24421494, 0.34739922, 0.50076587]]), 0.366717524789043)